export const assets = {
  pawIcon: '/assets/paw-icon.png',
  pawLogoLight: '/assets/paw-logo-light.png',
  pawLogoDark: '/assets/paw-logo-dark.png',
  pawPreviewLight: '/assets/paw-preview-light.png',
  pawPreviewDark: '/assets/paw-preview-dark.png',
  monoTextBlack: '/assets/mono-text-black.png',
  monoTextWhite: '/assets/mono-text-white.png',
  contactWechatIcon: '/assets/contact-wechat.png',
  contactTelegramIcon: '/assets/contact-telegram.png',
  themeLight: '/assets/default-theme-light.png',
  themeDark: '/assets/default-theme-dark.png',
}

export const siteContent = {
  hero: {
    title: 'mono',
    slogan: '世界很吵，留一点声音给自己。',
    lead: 'LOUD WORLD · QUIET SOUND',
  },
  purchase: {
    label: 'TestFlight 自助',
    href: '/testflight',
  },
  xianyu: {
    label: '闲鱼购买',
    href: 'https://www.goofish.com/item?spm=a21ybx.search.searchFeedList.1.50f356737tcUxU&id=1033040336894&categoryId=201459411',
    lead: '如果 TestFlight 名额、保护码或自动邀请遇到问题，可以通过闲鱼购买后联系开发者处理。',
  },
  contact: {
    label: '联系开发者',
    copiedLabel: '已复制微信号',
    dialogTitle: '联系开发者',
    dialogMessage: '请选择一种联系方式。',
    dialogAction: '关闭',
    wechatLabel: '微信联系',
    telegramLabel: 'TG 频道',
    telegramHref: 'https://t.me/+uRk4HLk65fk4MjE1',
    telegramName: 'Mono - 用户交流反馈',
    telegramCode: '+uRk4HLk65fk4MjE1',
    value: 'Fallin-Out0122',
  },
  tokenQuery: {
    label: 'Token 查询',
    title: 'Token 查询',
    lead: '输入邮箱、用户名或 Token，找回你的授权信息。',
    placeholder: '邮箱 / 用户名 / Token',
    submitLabel: '查询',
    loadingLabel: '查询中...',
    emptyMessage: '没有找到匹配的 Token。',
    copyLabel: '复制 Token',
    copiedLabel: '已复制',
  },
  updates: {
    label: '更新公告',
    title: '更新公告',
    lead: '查看 mono 最新版本与更新内容。',
    latestLabel: 'Latest Release',
    downloadLabel: '下载最新版本',
    archiveLabel: '历史版本',
    emptyMessage: '暂无可用更新公告。',
  },
  ipaDownload: {
    label: '自签 IPA 下载',
    href: '/download',
  },
  testflight: {
    label: 'TestFlight 自助',
    title: 'TestFlight 自助邀请',
    lead: '填写姓名、邮箱和保护码，系统会自动把你加入 TestFlight 测试组。',
    slug: '53453df19adbba61bdf2d399',
    namePlaceholder: '你的姓名',
    emailPlaceholder: '用于接收 TestFlight 邀请的邮箱',
    protectCodePlaceholder: '保护码',
    submitLabel: '提交邀请',
    trialLabel: '免保护码体验 1 小时',
    loadingLabel: '处理中...',
    successTitle: '已提交邀请',
    tokenLabel: '专属 Token',
    copiedLabel: '已复制',
    copyLabel: '复制 Token',
    publicLinkLabel: '前往邮箱',
  },
  footer: {
    appName: 'mono',
    developer: 'Developed by ZIJIU522',
  },
}
